# ===============
# Data Parameters
# ===============
data:
  features:
    - building_id_meter1
    - meter_meter1
    - timestamp_month_meter1
    - timestamp_day_meter1
    - timestamp_weekday_meter1
    - timestamp_isholiday_meter1
    - site_id_meter1
    - primary_use_meter1
    - square_feet_meter1
    - year_built_meter1
    - floor_count_meter1
    - square_feet_div_floor_count_meter1
    - square_feet_div_mean_by_site_id_meter1
    - square_feet_div_mean_by_primary_use_meter1
    - square_feet_div_mean_by_year_built_meter1
    - max_air_temperature_meter1
    - std_air_temperature_meter1
    - min_air_temperature_meter1
    - mean_air_temperature_meter1
    - diff_min_air_temperature_from_pre_1d_meter1
    - diff_min_air_temperature_from_pre_7d_meter1
    - diff_max_air_temperature_from_pre_1d_meter1
    - diff_max_air_temperature_from_pre_7d_meter1
    - diff_std_air_temperature_from_pre_1d_meter1
    - diff_std_air_temperature_from_pre_7d_meter1
    - diff_mean_air_temperature_from_pre_1d_meter1
    - diff_mean_air_temperature_from_pre_7d_meter1
    - max_cloud_coverage_meter1
    - std_cloud_coverage_meter1
    - min_cloud_coverage_meter1
    - mean_cloud_coverage_meter1
    - diff_min_cloud_coverage_from_pre_1d_meter1
    - diff_min_cloud_coverage_from_pre_7d_meter1
    - diff_max_cloud_coverage_from_pre_1d_meter1
    - diff_max_cloud_coverage_from_pre_7d_meter1
    - diff_std_cloud_coverage_from_pre_1d_meter1
    - diff_std_cloud_coverage_from_pre_7d_meter1
    - diff_mean_cloud_coverage_from_pre_1d_meter1
    - diff_mean_cloud_coverage_from_pre_7d_meter1
    - max_dew_temperature_meter1
    - std_dew_temperature_meter1
    - min_dew_temperature_meter1
    - mean_dew_temperature_meter1
    - diff_min_dew_temperature_from_pre_1d_meter1
    - diff_min_dew_temperature_from_pre_7d_meter1
    - diff_max_dew_temperature_from_pre_1d_meter1
    - diff_max_dew_temperature_from_pre_7d_meter1
    - diff_std_dew_temperature_from_pre_1d_meter1
    - diff_std_dew_temperature_from_pre_7d_meter1
    - diff_mean_dew_temperature_from_pre_1d_meter1
    - diff_mean_dew_temperature_from_pre_7d_meter1
    - max_precip_depth_1_hr_meter1
    - std_precip_depth_1_hr_meter1
    - min_precip_depth_1_hr_meter1
    - mean_precip_depth_1_hr_meter1
    - diff_min_precip_depth_1_hr_from_pre_1d_meter1
    - diff_min_precip_depth_1_hr_from_pre_7d_meter1
    - diff_max_precip_depth_1_hr_from_pre_1d_meter1
    - diff_max_precip_depth_1_hr_from_pre_7d_meter1
    - diff_std_precip_depth_1_hr_from_pre_1d_meter1
    - diff_std_precip_depth_1_hr_from_pre_7d_meter1
    - diff_mean_precip_depth_1_hr_from_pre_1d_meter1
    - diff_mean_precip_depth_1_hr_from_pre_7d_meter1
    - max_sea_level_pressure_meter1
    - std_sea_level_pressure_meter1
    - min_sea_level_pressure_meter1
    - mean_sea_level_pressure_meter1
    - diff_min_sea_level_pressure_from_pre_1d_meter1
    - diff_min_sea_level_pressure_from_pre_7d_meter1
    - diff_max_sea_level_pressure_from_pre_1d_meter1
    - diff_max_sea_level_pressure_from_pre_7d_meter1
    - diff_std_sea_level_pressure_from_pre_1d_meter1
    - diff_std_sea_level_pressure_from_pre_7d_meter1
    - diff_mean_sea_level_pressure_from_pre_1d_meter1
    - diff_mean_sea_level_pressure_from_pre_7d_meter1
    - max_wind_direction_meter1
    - std_wind_direction_meter1
    - min_wind_direction_meter1
    - mean_wind_direction_meter1
    - diff_min_wind_direction_from_pre_1d_meter1
    - diff_min_wind_direction_from_pre_7d_meter1
    - diff_max_wind_direction_from_pre_1d_meter1
    - diff_max_wind_direction_from_pre_7d_meter1
    - diff_std_wind_direction_from_pre_1d_meter1
    - diff_std_wind_direction_from_pre_7d_meter1
    - diff_mean_wind_direction_from_pre_1d_meter1
    - diff_mean_wind_direction_from_pre_7d_meter1
    - max_wind_speed_meter1
    - std_wind_speed_meter1
    - min_wind_speed_meter1
    - mean_wind_speed_meter1
    - diff_min_wind_speed_from_pre_1d_meter1
    - diff_min_wind_speed_from_pre_7d_meter1
    - diff_max_wind_speed_from_pre_1d_meter1
    - diff_max_wind_speed_from_pre_7d_meter1
    - diff_std_wind_speed_from_pre_1d_meter1
    - diff_std_wind_speed_from_pre_7d_meter1
    - diff_mean_wind_speed_from_pre_1d_meter1
    - diff_mean_wind_speed_from_pre_7d_meter1
    - site_id_primary_use_meter1
    - target_encoding_by_building_id_folds1_meter1
    - target_encoding_by_site_id_folds1_meter1
    - target_encoding_by_primary_use_folds1_meter1
    - diff_min_air_temperature_from_pre_m1d_meter1
    - diff_max_air_temperature_from_pre_m1d_meter1
    - diff_std_air_temperature_from_pre_m1d_meter1
    - diff_mean_air_temperature_from_pre_m1d_meter1
    - diff_min_cloud_coverage_from_pre_m1d_meter1
    - diff_max_cloud_coverage_from_pre_m1d_meter1
    - diff_std_cloud_coverage_from_pre_m1d_meter1
    - diff_mean_cloud_coverage_from_pre_m1d_meter1
    - diff_min_dew_temperature_from_pre_m1d_meter1
    - diff_max_dew_temperature_from_pre_m1d_meter1
    - diff_std_dew_temperature_from_pre_m1d_meter1
    - diff_mean_dew_temperature_from_pre_m1d_meter1
    - diff_min_precip_depth_1_hr_from_pre_m1d_meter1
    - diff_max_precip_depth_1_hr_from_pre_m1d_meter1
    - diff_std_precip_depth_1_hr_from_pre_m1d_meter1
    - diff_mean_precip_depth_1_hr_from_pre_m1d_meter1
    - diff_min_sea_level_pressure_from_pre_m1d_meter1
    - diff_max_sea_level_pressure_from_pre_m1d_meter1
    - diff_std_sea_level_pressure_from_pre_m1d_meter1
    - diff_mean_sea_level_pressure_from_pre_m1d_meter1
    - diff_min_wind_direction_from_pre_m1d_meter1
    - diff_max_wind_direction_from_pre_m1d_meter1
    - diff_std_wind_direction_from_pre_m1d_meter1
    - diff_mean_wind_direction_from_pre_m1d_meter1
    - diff_min_wind_speed_from_pre_m1d_meter1
    - diff_max_wind_speed_from_pre_m1d_meter1
    - diff_std_wind_speed_from_pre_m1d_meter1
    - diff_mean_wind_speed_from_pre_m1d_meter1
  categorical_features: 

  fold_name: 02_gkfold_meter1

  drop_fname: drop_idx_meter1.npy
  
  convert_type: 'log'

  oof: 
    save_oof: True
    concat_oof:

# ===============
# Model Parameters
# ===============
model_params:
  objective: regression
  boosting_type: gbdt
  metric: rmse
  n_jobs: -1
  learning_rate: 0.05
  num_leaves: 256
  max_depth: 8
  colsample_bytree: 0.8
  subsample_freq: 1
  subsample: 0.8
  max_bin: 255
  verbose: -1
  random_state: 2019